Update api_def_Angle.pbtxt
The Example code shown in the api_def_Angle.pbtxt still using 1.x version code which will throw AttributeError: module 'tensorflow' has no attribute 'angle' if used in 2.x. Hence updating the example code suitable to 2.x version. Please also refer attached gist for details. https://colab.research.google.com/gist/SuryanarayanaY/c57df5a25572e7daebea235c633ce593/tf-math-angle.ipynb